version: '3.9'

services:
  java_db:
    container_name: java_db
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=java_db
    volumes:
      - java_db_data:/var/lib/postgresql/data

volumes:
  java_db_data: {}
    
  